### ISSUE TITLE
Not work for me 

### ISSUE THREAD

**Issue by yusei8** [K1utzer/Chess.com-bot#7]
PS C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot> python -m bot.py
WARNING: Developed with Python version 3.8.8. May not work properly if used with another version
C:\Users\MSI\AppData\Local\Programs\Python\Python310\python.exe: No module named bot.py
PS C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot>

**Comment by yusei8** [comment]
WARNING: Developed with Python version 3.8.8. May not work properly if used with another version
Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 790, in get
    value = d[option]
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'path_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot\bot.py", line 41, in <module>
    stockfish_path_name = str(config.get("stockfish", "path_name"))
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 793, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'path_name' in section: 'stockfish'
PS C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot>

**Comment by yusei8** [comment]
how to add path correctly

**Comment by yusei8** [comment]
[stockfish]
path= stockfish_15_x64.exe


not work give same error

**Comment by lutzwolfer** [comment]
change "path" to "path_name" in the config.cfg. In the latest commit it the latests commit it should work with "path"

**Comment by yusei8** [comment]
i think the path is fixed now but look i got another error  help plz
PS C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot> python bot.py
WARNING: Developed with Python version 3.8.8. May not work properly if used with another version
Traceback (most recent call last):
  File "C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot\bot.py", line 42, in <module>
    username = str(config.get("chess.com", "username"))
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'chess.com'

**Comment by lutzwolfer** [comment]
Download the latest version #6  and it should be fixed. The config.py should look like `import configparser

class Config:
    def __init__(self):
        config = configparser.ConfigParser()
        config.read("config.cfg")
        self.stockfish_path_name = f"stockfish_path/{config.get('stockfish', 'path')}"`

**Comment by yusei8** [comment]
thanks for replying bro, i'm verry noob, 
Yes its the same in config.py
i have downloaded the latest version of the project

**Comment by yusei8** [comment]
plz can you give me more detail how to fix the problem thanks

**Comment by yusei8** [comment]
Same problems i tried to 
reinstall python
redownload the latest version
installed all req,

**Comment by yusei8** [comment]
help me bro

**Comment by lutzwolfer** [comment]
> i think the path is fixed now but look i got another error help plz PS C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot> python bot.py WARNING: Developed with Python version 3.8.8. May not work properly if used with another version Traceback (most recent call last): File "C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot\bot.py", line 42, in username = str(config.get("chess.com", "username")) File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get d = self._unify_values(section, vars) File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values raise NoSectionError(section) from None configparser.NoSectionError: No section: 'chess.com'

I can't reproduce your issue with the latest version. ile "C:\Users\MSI\Desktop\Nouveau dossier\Chess.com-bot\bot.py", line 42, in username = str(config.get("chess.com", "username") this also tells me, that you're not using the latest version

**Comment by yusei8** [comment]
what python should i use for windows ????

**Comment by lutzwolfer** [comment]
It's developed with Python version 3.8.8

**Comment by lutzwolfer** [comment]
Does your config.py in the bot folder looks like that?:
`import configparser

class Config:
    def __init__(self):
        config = configparser.ConfigParser()
        config.read("config.cfg")
        self.stockfish_path_name = f"stockfish_path/{config.get('stockfish', 'path')}"`

**Comment by lutzwolfer** [comment]
Does your config.py in the bot folder looks like that?:
`import configparser

class Config:
    def __init__(self):
        config = configparser.ConfigParser()
        config.read("config.cfg")
        self.stockfish_path_name = f"stockfish_path/{config.get('stockfish', 'path')}"`

**Comment by yusei8** [comment]
Hello there,

Yes its same , i reinstalled all, python version, and new files again github project, and now i got new errors

Traceback (most recent call last):
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot.py", line 20, in <module>
    from stockfishpy.stockfishpy import *
ModuleNotFoundError: No module named 'stockfishpy'

Help me plz

**Comment by lutzwolfer** [comment]
Start the bot with: python -m bot

**Comment by yusei8** [comment]
WARNING: Developed with Python version 3.8.8. May not work properly if used with another version
Traceback (most recent call last):
  File "C:\Users\lorri\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lorri\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\__main__.py", line 1, in <module>
    from .Manager import main
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\Manager.py", line 5, in <module>
    from PyQt5 import QtGui, uic
ModuleNotFoundError: No module named 'PyQt5'

**Comment by lutzwolfer** [comment]
Try: "pip install pyqt5" first

**Comment by yusei8** [comment]
E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master>python -m bot
WARNING: Developed with Python version 3.8.8. May not work properly if used with another version
Traceback (most recent call last):
  File "C:\Users\lorri\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lorri\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\__main__.py", line 1, in <module>
    from .Manager import main
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\Manager.py", line 10, in <module>
    from .config import Config
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\config.py", line 4
    def init(self):
    ^
IndentationError: expected an indented block after class definition on line 3

**Comment by yusei8** [comment]
bro same errors 

E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master>python -m bot
WARNING: Developed with Python version 3.8.8. May not work properly if used with another version
Traceback (most recent call last):
  File "C:\Users\lorri\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lorri\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\__main__.py", line 1, in <module>
    from .Manager import main
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\Manager.py", line 10, in <module>
    from .config import Config
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\config.py", line 1
    `import configparser
    ^
SyntaxError: invalid syntax

**Comment by yusei8** [comment]
its worked, the program start but the bot not work i dont know why 


06/22/2022 09:46:26 AM - chessbot_logger - INFO - Init Main Window
06/22/2022 09:46:57 AM - chessbot_logger - WARNING - Board not detected
06/22/2022 09:47:00 AM - chessbot_logger - INFO - Board detected
06/22/2022 09:47:34 AM - chessbot_logger - INFO - Started bot. Games played: 0
Traceback (most recent call last):
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\Manager.py", line 66, in run
    self.field_Cords, self.myturn = imageDet.calculate_field_cords(
  File "E:\Downloadsz\Chess.com-bot-master\Chess.com-bot-master\bot\ImageDetection.py", line 64, in calculate_field_cords
    if screenimg[top_left[1]+int(field_h/2), start_X+int(field_w/2)][0] > 200 and screenimg[top_left[1]+int(field_h/2), start_X+int(field_w/2)][1] > 200 and screenimg[top_left[1]+int(field_h/2), start_X+int(field_w/2)][2] > 200:
IndexError: index 117187960 is out of bounds for axis 0 with size 1080

**Comment by keremyesildag** [comment]
I downloaded all the modules but when I say start bot I get an index error

**Comment by lutzwolfer** [comment]
Which Python version are you using?

**Comment by K1utzer** [comment]
Closed, because of duplicate IndexError. Write in IndexError issue

**Comment by lutzwolfer** [comment]
Closed, because of duplicate IndexError. Write in IndexError issue
